version: '3'

services:
  app:
    image: registry.gitlab.com/pathto/myapp:prod
    environment:
      DJANGO_SETTINGS_MODULE: modern_devops.settings.prod
    volumes:
      - /var/data/myapp/prod/settings.py:/site/modern_devops/settings/prod.py:ro
    depends_on:
      - postgresql
      - redis
    networks:
      - default
      - public

  postgresql:
    image: postgres:10-alpine
    volumes:
      - /var/data/realtime/myapp/prod/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: myapp_staging
      POSTGRES_PASSWORD: myapp_staging
      POSTGRES_DB: myapp_staging

  redis:
    image: redis:latest

networks:
  public:
    external: true
